# Generated by Django 5.2.6 on 2025-10-10 16:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('KES', 'Kenyan Shilling'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('GBP', 'British Pound Sterling'), ('JPY', 'Japanese Yen'), ('EUR', 'Euro'), ('USD', 'US Dollar')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_return', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rental',
                'verbose_name_plural': 'Rentals',
                'ordering': ['-created_at'],
            },
        ),
    ]
