# Generated by Django 5.2.6 on 2025-09-26 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_customuser_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycprofile',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='kycprofile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='kycprofile',
            name='submitted_at',
        ),
        migrations.AlterField(
            model_name='kycprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='kycprofile',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='kycprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
