# Generated by Django 5.2.6 on 2025-09-26 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_kycprofile_id_number_kycprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kycprofile',
            old_name='id_number',
            new_name='national_id',
        ),
    ]
