# Generated by Django 5.2.6 on 2025-12-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_rename_id_number_kycprofile_national_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='wallet_balance',
        ),
        migrations.AddField(
            model_name='referral',
            name='rental_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='referral',
            name='reward_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='referral',
            name='reward_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='referral',
            name='reward',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
