# Generated by Django 5.2.6 on 2025-12-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_mpesatransactionmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='rental_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
