# Generated by Django 5.2.5 on 2025-09-11 14:10

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(default=Users.models.generate_referral_code, max_length=12, unique=True),
        ),
    ]
