# Generated by Django 5.2.6 on 2025-10-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['-last_updated'], 'verbose_name': 'Wallet', 'verbose_name_plural': 'Wallets'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('KES', 'Kenyan Shilling'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('GBP', 'British Pound Sterling'), ('JPY', 'Japanese Yen'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='KES', max_length=3),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20),
        ),
    ]
