# Generated by Django 5.2.6 on 2025-10-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_payment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_request_id',
            field=models.CharField(blank=True, help_text='M-PESA CheckoutRequestID for STK Push tracking', max_length=50, null=True),
        ),
    ]
