# Generated by Django 5.2.6 on 2025-12-02 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_checkout_request_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransactionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_request_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'M-PESA Transaction Mapping',
                'verbose_name_plural': 'M-PESA Transaction Mappings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['checkout_request_id'], name='payment_mpe_checkou_7263bb_idx'), models.Index(fields=['expires_at'], name='payment_mpe_expires_351c75_idx')],
            },
        ),
    ]
