# Generated by Django 5.2.6 on 2025-10-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Enable maintenance mode to restrict access for non-admins')),
                ('email_notifications', models.BooleanField(default=True, help_text='Enable email notifications for system events')),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
